### ISSUE TITLE
the converter doesn't support @use

### ISSUE THREAD

**Issue by Mikelantonio** [jekyll/jekyll-sass-converter#105]
Hello,

I'm trying to use the last version of [mdc card](https://github.com/material-components/material-components-web/tree/master/packages/mdc-card) on jekyll 4.

I should add these lines of code to my scss file
`@use "@material/card";
@include card.core-styles;`

When I run the compiler, I have the following error

`Invalid CSS after "@include card": expected 1 selector or at-rule, was ".core-styles;"`

I've found a similar issue about the node-saas converter [here](https://github.com/material-components/material-components-web/issues/5631)

Can it be the same problem? Using a previous version of mdc card that uses @import it works.
Thanks in advance

**Comment by DirtyF** [comment]
https://sass-lang.com/documentation/at-rules/use 

> Only Dart Sass currently supports @use. Users of other implementations must use the @import rule instead.
