### ISSUE TITLE
Config: sass_dir doesn't accept array

### ISSUE THREAD

**Issue by supergibbs** [jekyll/jekyll-sass-converter#107]
Documentation says sass_dir is `An array of filesystem-paths which should be searched for Sass partials.` but is actually a string. An array breaks the compilation here [lib/jekyll/converters/scss.rb#L127](https://github.com/jekyll/jekyll-sass-converter/blob/master/lib/jekyll/converters/scss.rb#L127)

**Comment by ashmaroli** [comment]
Nice catch @supergibbs.
It is a documentation error.

If you were to trace the history of the line of code you posted, you'll see that `sass_dir` has always been a string.

I'll let you have the honor of submitting a pull request to correct the README document.
The gist is that `sass_dir` is a string but `load_paths` is an array.

**Comment by supergibbs** [comment]
Ah ok, thanks. PR submitted!
