### ISSUE TITLE
max(), min() not working properly

### ISSUE THREAD

**Issue by timharek** [jekyll/jekyll-sass-converter#118]
I'm having issues with using `max()` and `min()`.

I have the following code:
```scss
width: min(760px, 70%)
```

Then I get the following compile error:
```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main.scss':
                    Internal Error: Incompatible units: '%' and 'px'.
             Error: Internal Error: Incompatible units: '%' and 'px'.
```

When I try to do the same with pure CSS it works fine.

**Comment by rsampaths16** [comment]
I believe the issue is with SASS and not Jekyll. Check this out and see if it helps : https://github.com/sass/node-sass/issues/2815

**Comment by timharek** [comment]
Ah, alright! Thank you, I will use the workaround suggested in that thread :)
