### ISSUE TITLE
jekyll-sass-converter v3 doesn't build on Alpine (musl)

### ISSUE THREAD

**Issue by nmarley** [jekyll/jekyll-sass-converter#147]
This is apparently because the dependency dart-sass-embedded has not been built or supported for musl at https://github.com/sass/dart-sass-embedded/releases/tag/1.57.1.

Here's my error message:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /app/vendor/ruby/3.1.0/gems/sass-embedded-1.57.1/ext/sass
/usr/bin/ruby -I/usr/local/lib/site_ruby/3.1.0 -rrubygems /app/vendor/ruby/3.1.0/gems/rake-13.0.6/exe/rake
RUBYARCHDIR\=/app/vendor/ruby/3.1.0/extensions/x86_64-linux-musl/3.1.0/sass-embedded-1.57.1
RUBYLIBDIR\=/app/vendor/ruby/3.1.0/extensions/x86_64-linux-musl/3.1.0/sass-embedded-1.57.1
rake aborted!
NotImplementedError: sass_embedded for x86_64-linux-musl not available at
https://github.com/sass/dart-sass-embedded/releases/tag/1.57.1
/app/vendor/ruby/3.1.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:226:in `default_sass_embedded'
/app/vendor/ruby/3.1.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:21:in `block (2 levels) in <top (required)>'
/app/vendor/ruby/3.1.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:21:in `fetch'
/app/vendor/ruby/3.1.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:21:in `block in <top (required)>'
/app/vendor/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<main>'
Tasks: TOP => default => install => embedded.rb => sass_embedded
(See full trace by running task with --trace)

rake failed, exit code 1
```

**Comment by ntkme** [comment]
This is expected. The Dart VM still do not have support for musl-libc at this point: https://github.com/dart-lang/sdk/issues/40906

Please consider switch to a glibc based linux. If you cannot switch somehow, you can lock jekyll-sass-converter to 2.x in Gemfile, but you’re stuck with the old version of sass that way.

**Comment by nmarley** [comment]
Thanks for the suggestion! I was able to lock to version 2 in the Gemfile and get the gem installed as usual.

**Comment by amyspark** [comment]
Hi! Just found this issue when searching for jekyll/jekyll/9132. I had to dig into the Rakefile to understand the error, as there was no documentation on how the Dart Sass executable was sourced.

Would it be possible for this to get listed in the 3.x migration checklist, so that others don't run into the same problem?

**Comment by ashmaroli** [comment]
Updated the README to mention lack of Dart VM support on linux-musl platform.

**Comment by anna328p** [comment]
is there any way to be able to specify the location of the Dart Sass executable? I use NixOS which can't run arbitrary unpatched binaries, but there's a package that provides the version transpiled to Node.

**Comment by ashmaroli** [comment]
ping @ntkme for inputs regarding above query :point_up_2:

**Comment by ntkme** [comment]
> is there any way to be able to specify the location of the Dart Sass executable? I use NixOS which can't run arbitrary unpatched binaries, but there's a package that provides the version transpiled to Node.

Discussion here: https://github.com/ntkme/sass-embedded-host-ruby/pull/91

**Comment by ntkme** [comment]
Alpine (musl) will be supported in next release of sass-embedded gem. I will send a PR to update README once it is available.
