### ISSUE TITLE
No CSS file being output

### ISSUE THREAD

**Issue by brianmaierjr** [jekyll/jekyll-sass-converter#149]
I'd really like to replace my existing Gulp flow with this plugin but can't seem to get it working. I have it set up exactly like the example from the Jekyll documentation but it still outputs `style.scss` in the `_site/assets/css/` folder with all the @imports like the original sass file. I'm sure that I'm missing something small. I have my changes pushed to a branch if you wouldn't mind taking a look https://github.com/brianmaierjr/long-haul/tree/remove-gulp

**Comment by ashmaroli** [comment]
Hello @brianmaierjr
For `assets/css/styles.scss` to be output into `_site/assets/css/styles.css`, the source file needs to have front matter, albeit empty:
```
---
---

// Reset using Normalise
@import "normalize";

[...]
```
