### ISSUE TITLE
sass 3.4.0 -> 3.4.2 appears to break converter

### ISSUE THREAD

**Issue by pearsonca** [jekyll/jekyll-sass-converter#22]
I was getting strange site breaks starting this afternoon that I couldn't replicate on my machine (at sass 3.4.0).  I noticed that Travis CI indicated that the jekyll bundle was now using 3.4.2 (which hit today), so I upgraded and now I get the site breaks locally as well.

I've tried running upgraded sass against my source and get no errors, so presumably a problem in this plugin is what's causing:

`Conversion error: Jekyll::Converters::Scss encountered an error converting 'css/my.scss'`

I'm not savvy enough to get it to give me something more informative, or I'd tell you more.

Also, this error does _not_ fail the site build.  Not sure how that works, but it definitely should.

**Comment by tomjohnson1492** [comment]
For some reason, I'm getting errors from having Liquid in Sass. Here's the error msg:

```
Conversion error: Jekyll::Converters::Scss encountered an error converting 'stylesheets/jboot.scss'.
  Conversion error: Invalid CSS after " $theme-color: ": expected expression (e.g. 1px, bold), was "$;"
```

From looking at this thread, it seems Liquid was removed and then re-added to Sass, but maybe it was removed again?

Here's my Liquid in Sass:

```
{% unless site.data.theme.color == "default" %}
  $theme-color: ${{ site.data.theme.color }};
  $navbar-inverse-bg: $theme-color;
  @if $theme-color == $dark {
    $brand-primary: $dark-brand-primary;
  } @else {
    $brand-primary: $theme-color;
  }
{% endunless %}
```

Are there only certain Liquid tags allowed in Sass? Should I be getting these error messages or not?
