### ISSUE TITLE
Having the main Sass files in the CSS directory is unexpected

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll-sass-converter#33]
I think, it should be possible (or the default) to have the main Sass file(s) (e.g. the file that imports the partials) in `sass_dir`. Currently, when it’s there, it is not being picked up by Jekyll.

__But__ then again, the created CSS file would be in `sass_dir` as well. Not optimal either. What do you think about this?

**Comment by parkr** [comment]
We can't stray too far from Jekyll norms. By saying "Create a page, and use the .scss or .sass file extension", it makes sense. I write a page like any other page: I add the folders necessary, and add the file with the front matter. It's already a construct in Jekyll – nothing new to learn. Then, one can say "if you would like to import Sass/SCSS into that page, put your partials in `sass_dir`, which is `_sass` by default. Our documentation might not do a good job of explaining that (my fault) but I think the process is consistent with the rest of the tool.

**Comment by kleinfreund** [comment]
Alright, cool. Just wanted to kick in some thoughts and shed some light on this, because I had no clear opinion on it. Thanks. :)
