### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-sass-converter#35]
Somewhat related to #20, it would be cool if **jekyll-sass-converter** could be used with [**autoprefixer**](https://github.com/postcss/autoprefixer).

There exists a [Ruby port](https://github.com/ai/autoprefixer-rails), but it works on files, not blobs. Not sure how to make this work...

**Comment by parkr** [comment]
If you can figure out a way to make it work on blobs, that'd be the first step!
