### ISSUE TITLE
avoid creating sass-cache in the current directory

### ISSUE THREAD

**Issue by samuelrivas** [jekyll/jekyll-sass-converter#49]
Is there a way not to create the .sass-cache file in the current directory?

I am running `jekyll build --destination $DEST` in a setting where the current directory is readonly and the only way I found to make it work is to set `safe` to `true`.

**Comment by parkr** [comment]
I believe this does it for you, in your `_config.yml`:

```yaml
sass:
  cache: false
```

**Comment by samuelrivas** [comment]
Yes, but that does more than just keeping .sass-cache out of the current directory. I already mentioned that that was the only way I found to avoid it, but is less than ideal
