### ISSUE TITLE
The new release requires an unavailable version of sassc

### ISSUE THREAD

**Issue by chdiza** [jekyll/jekyll-sass-converter#92]
```
$ gem update jekyll-sass-converter
Updating installed gems
Updating jekyll-sass-converter
ERROR:  Error installing jekyll-sass-converter:
	Unable to resolve dependency: 'jekyll-sass-converter (= 2.0.0)' requires 'sassc (> 2.0.1, < 3.0)'
Nothing to update
```

OK, so if I then try `gem install sassc` to satisfy this dependency, then `gem` downloads and installs  version 2.0.1 of `sassc` which will not satisfy the dependency.  Versions of `sassc` higher than 2.0.1 have the status "prerelease".

**Comment by ashmaroli** [comment]
@chdiza `sassc-2.1.0` has been released couple of minutes ago. Please try again

**Comment by chdiza** [comment]
OK, that works now.  But there were several days when updating was impossible.
