### ISSUE TITLE
Incompatible with gem-based themes in safe mode

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-sass-converter#95]
Because the plugin [sanitizes all load paths relative to the site source](https://github.com/jekyll/jekyll-sass-converter/blob/master/lib/jekyll/converters/scss.rb#L130-L133), gem-based themes cannot use sass in safe mode.

Steps to reproduce:

1. Create (or use an existing) theme that relies on sass
2. Require the theme in you confirm
3. Build the site in safe mode

Expected:

Theme's sass load path outside the site root is included as a load path and build succeeds with sass converted to CSS

Actual:

Build failed due to missing includes.

/cc https://github.com/benbalter/jekyll-remote-theme/issues/58

**Comment by ashmaroli** [comment]
Thank you for reporting this @benbalter. I've submitted a PR for review :point_up_2:
